name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: glfw
      run: sudo apt-get install libglfw-dev
    - name: make
      run: make
    - name: application
      run: ./application
    - name: clean
      run: make clean


